version: '3'
services:
  # database config
  database:
    image: 'mongo'
    container_name: 'my-mongo-container2020'
    environment:
      - MONGO_INITDB_DATABASE=airportDb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # copy initdb.js to /docker-entrypoint-initdb.d/ as a read only file.
      - ./database/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - ./database/mongo-volume:/data/db
      # do db initial load
      - ./database/airport-data.js:/docker-entrypoint-initdb.d/airport-data.js:ro
    ports:
      - '27017:27017'

