openapi: 3.0.0
info:
  title: Airport RESTful API
  description: This api allows you to get information about all or specific airports located across the globe.
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/airports
    description: local development environment
paths:
  /airports:
    get:
      summary: Returns a list of all available airports.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    post:
      summary: Returns a list of all available airports.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string